[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bcm2835-lpa = "0.4.0"
log = { version = "0.4.25", default-features = false }
pi0-register = { version = "0.1.0", path = "../pins" }

[[bin]]
name = "rust"
path = "src/main.rs"
test = false
doctest = false
bench = false

